#     ___      ___       __        __    ___       ___      ___   _______
#    |"  \    /"  |     /""\      |" \  |"  |     |"  \    /"  | /"     "|
#     \   \  //   |    /    \     ||  | ||  |      \   \  //   |(: ______)
#     /\\  \/.    |   /' /\  \    |:  | |:  |      /\\  \/.    | \/    |
#    |: \.        |  //  __'  \   |.  |  \  |___  |: \.        | // ___)_
#    |.  \    /:  | /   /  \\  \  /\  |\( \_|:  \ |.  \    /:  |(:      "|
#    |___|\__/|___|(___/    \___)(__\_|_)\_______)|___|\__/|___| \_______)

# @Author Harry0198 / Harolds

#
# ◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥
#                     How to use the plugin
#   Most of this plugin should be self explanatory. Lots of values
#           Are commented out for your ease of use.
#
#   Alternatively, see plugin page for more help!
#
# ◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥◤◢◣◥
#

#                              Global Modifiers
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━▼━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#

  # This is the default global language that is used across the server if one is not selected
# Default "EN"
lang: "EN"

# This is the delay before you can send another mail to the recipient in minutes
# Default 1
delay: 1

# Turns debug mode on / off
# Default false (off)
debug: false

#                              Icons for usage
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━▼━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#

# Default icons:
# There is no limit to these so you can just add more and it will make new pages like normal.
# If a mistake is made an error will be thrown.
# To add more, simply copy and paste one path below and edit the "type" to a valid Material.

icons:
  item1:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: SEA_PICKLE
  item2:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: OAK_SIGN
  item3:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: LECTERN
  item4:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: DIAMOND_PICKAXE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        DIG_SPEED: 4
  item5:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: MINECART
  item6:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: ELYTRA
  item7:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: WHITE_BANNER
    meta:
      ==: ItemMeta
      meta-type: BANNER
      patterns:
        - ==: Pattern
          color: RED
          pattern: ss
        - ==: Pattern
          color: GREEN
          pattern: bri